# Generated by Django 2.0.5 on 2018-05-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_tex',
            new_name='choice_text',
        ),
    ]
